schema_version: 1

context:
  version: "0.6.0"
  python_min: "3.11"

package:
  name: altimetry-downloader-aviso
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/altimetry-downloader-aviso/altimetry_downloader_aviso-${{ version }}.tar.gz
  sha256: 1aeb12f08eaea20fbc871480141b35d857f0609aeab3b4ded2bcc48c66903bd7

build:
  noarch: python
  number: 0
  python:
    entry_points:
      - altimetry-downloader-aviso = altimetry_downloader_aviso.cli:app

  script:
    - python -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
    - setuptools-scm
  run:
    - numpy
    - python >=${{ python_min }}
    - requests
    - typer
    - siphon
    - rich
    - files_collections >=2
    - altimetry-search >=2.1.0
    - pyyaml
    - pydantic
    - h5netcdf
    - netCDF4
    - xarray

tests:
  - python:
      pip_check: true
      imports:
        - altimetry_downloader_aviso
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: "Altimetry Downloader Aviso — Browse and download altimetry data from Aviso"
  license: Apache-2.0
  homepage: https://github.com/robin-cls/aviso
  repository: https://github.com/robin-cls/aviso
  license_file: LICENSE

extra:
  recipe-maintainers:
    - annesophie-cls
    - robin-cls
